Future<void> futuresAsync() async {
  var demo = await Future(() => 5);
  demo++;
  print(demo);

  // try {
  //   // var demo = await Future(() => 5);
  //   var demo = await Future(() => throw Exception);
  //   demo++;
  //   print('ðŸŽ‰  $demo');
  // } catch (error) {
  //   print('ðŸ”¥  $error');
  // } finally {
  //   print('âœ…  Complete!');
  // }
}
